### ISSUE TITLE
Sizes of SS are too big.

### ISSUE THREAD

**Issue by UvrajSB** [shashankRanaNoidaWala/features_and_bugs_of_CSA_times#2]
Try using image tags and give proper height and width
https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown

**Comment by shashankRanaNW** [comment]
Changed the size of images to 200.
https://github.com/shashankRanaNoidaWala/features_and_bugs_of_CSA_times/commit/80b0459f26a4d20542fa85110f90db408c57ad9c
<img src="https://user-images.githubusercontent.com/101785829/182760444-3c7e89b7-0a44-48f8-983d-587e964690f0.png" width="200" />
